

# Neon PostgreSQL Database URL
DATABASE_URL="postgresql://neondb_owner:npg_fX9A1eWquyHj@ep-old-waterfall-ad2ro4a5-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"

# FastAPI Backend URL
API_BASE_URL = "https://biometric-attendance-system-black.vercel.app"
